### PR TITLE
copy weights to enable in-place modification of w

### PR DESCRIPTION
**Pull request by rubenfiszel**

### CODE REVIEW

**Comment by martinjaggi** [comment]
thanks!

**Comment by IamTao** [comment]
The copy here is actually not necessary.
You can check this blog [Is Python call-by-value or call-by-reference? Neither](https://jeffknupp.com/blog/2012/11/13/is-python-callbyvalue-or-callbyreference-neither/) for more details.

**Comment by rubenfiszel** [comment]
I am not sure why this post implies that the copy isn't necessary. 

The patch here is to enable in-place modification of w.

By appending w to the list without any copy, we're in fact appending the same w over and over.

It is of course not an issue if w is not modified in-place.

**Comment by SeguinBe** [comment]
It is a matter of implementation indeed, it might be necessary or not depending on the way you perform the operations :

```python
import numpy as np

ws_inplace, ws = [], []
w_inplace, w = np.array([0.0, 0.0]), np.array([0.0, 0.0])
w_update = np.array([0.1, 0.1])

ws.append(w), ws_inplace.append(w_inplace)
w = w + w_update
w_inplace += w_update  # or w_inplace[:] = w_inplace + w_update
ws.append(w), ws_inplace.append(w_inplace)

print(ws, ws_inplace)
```

**Pull request merged**
